# imgui_bundle pyodide package: manual action required
# ====================================================
# Before building this package, you need to trigger the build of 
# a sdl library with -fPIC (aka RELOCATABLE=1, within emscripten).
#
# Use this command to trigger it, from inside the pyodide repository:
#
# ```bash
#     # Activate emscripten
#     source emsdk/emsdk/emsdk_env.sh
#     # Create a fake project to trigger the build of the custom SDL2 library with -fPIC
#     # (aka RELOCATABLE=1, within emscripten)
#     echo 'int main() {}' | emcc -x c -sUSE_SDL=2 -sRELOCATABLE=1  - -o output.js && rm output.js && rm output.wasm
# ```
#
# See https://github.com/pyodide/pyodide/issues/5248:

package:
  name: imgui_bundle
  version: 1.6.1
  top-level:
    - imgui_bundle

# Prod
# source:
#   url: https://github.com/pthom/imgui_bundle/releases/download/v1.6.1/imgui_bundle-v1.6.1-pyodide.tgz
#   sha256: 7204ba4d1e7584dc632cc56874ddf12a08571b8ac60892e58312e7ab1b6cbb63

# Devel version
source:
  path: /home/pascal/dvp/_Bundle/imgui_bundle

