[build-system]
requires = ["scikit-build-core>=0.3.3", "nanobind"]
build-backend = "scikit_build_core.build"


[project]
name = "daft_lib"
version = "0.0.1"
description="daft-lib"
requires-python = ">=3.7"


[tool.scikit-build]
wheel.expand-macos-universal-tags = true
wheel.packages = ["src/python_bindings/daft_lib"]
cmake.verbose = true
logging.level = "INFO"
